// English translation of content/copy.ts — must keep exactly the same key
// shape as COPY_CS (enforced by the CopyShape type below; a missing or
// extra key here is a TypeScript compile error). Translations aim for
// natural English tone rather than literal word-for-word phrasing, except
// where the Czech is already a short game-UI label.
import type { CopyShape } from "./copy";

export const COPY_EN: CopyShape = {
  franchise: {
    title: "Night Watchman",
    fullTitleObject13: "Night Watchman: Object 13",
  },
  campaign: {
    object13: {
      title: "Object 13",
    },
  },
  menu: {
    title: "Night Watchman",
    subtitle: "Object 13: First Shift",
    intro: "You're sitting in a small room. The cameras hiss with static. The door won't hold forever. Survive till dawn.",
    goldenGuardIntro:
      "You're sitting in a small room. The cameras hiss with static. The door won't hold forever. Except this time, you're not the one who should be afraid.",
    startButton: "Start Shift",
    startButtonVeteran: "Start Veteran Shift",
    startButtonNightSuffix: "(night {night})",
    termsLinkLabel: "Terms of Night Duty",
    leaderboardLinkLabel: "Hall of Fame",
    profileLinkLabel: "Watchman Profile",
    authorEmail: "hynek@darbujan.com",
  },
  intro: {
    startIntroLabel: "Play Intro",
  },
  profile: {
    seoTitle: "Watchman Profile | Night Watchman",
    seoDescription: "Object 13 watchman profile — status, stats and achievements stored locally in your browser.",
    heading: "Watchman Profile",
    backToMenuLabel: "← Back to menu",
    serviceCardHeading: "Service Card",
    statusLabel: "Status",
    statusGolden: "GOLDEN WATCHMAN",
    statusRookie: "NIGHT WATCHMAN",
    rewardLabel: "Reward",
    rewardUnlocked: "Double-barrel shotgun unlocked",
    rewardLocked: "No reward unlocked yet",
    monsterDefeatsLabel: "Monster defeats",
    noteGolden: "This watchman has already taken down the beast. Object 13 is still standing, though.",
    noteRookie: "Just another name on the service card, for now.",
    hardcoreSourceServer: "Hardcore data source: server",
    hardcoreSourceLocal: "Hardcore data source: local profile",
    serverLoadFailedWarning: "Couldn't load the server Hardcore profile. Showing local data instead.",
    syncButtonLabel: "Sync Hardcore profile",
    syncButtonSyncing: "Syncing…",
    statsHeading: "Statistics",
    statsLocalNote: "Training and Hardcore activity combined for now — a local, non-competitive overview.",
    statTotalDeaths: "Total deaths",
    statTotalRunsStarted: "Shifts started",
    statTotalNightsSurvived: "Nights survived",
    statHardcoreBestNight: "Best Hardcore night",
    statBulbsReplaced: "Bulbs replaced",
    statGeneratorsRestarted: "Generators restarted",
    statExpeditionsStarted: "Expeditions started",
    statExpeditionsReturned: "Safe returns",
    statMonsterHitsConfirmed: "Confirmed hits",
    statMonsterKills: "Monsters killed",
    statHardcoreDeathsOnNightOne: "Deaths on night 1",
    achievementsHeading: "Achievements",
    achievementUnlockedMark: "✓",
    achievementLockedMark: "?",
    achievementHiddenTitle: "Unknown achievement",
    achievementHiddenDescription: "Unlock it to find out what it is.",
    loadoutHeading: "Loadout",
    loadoutDoubleBarrelName: "Double-barrel shotgun",
    loadoutDoubleBarrelNote: "Reward for the first monster defeat.",
    loadoutEmpty: "Loadout will be filled in as you earn it.",
    resetButtonLabel: "Reset local profile",
    resetConfirmLabel: "Really delete the local profile?",
  },
  gameMode: {
    normalLabel: "TRAINING",
    hardcoreLabel: "HARDCORE",
    normalTooltip: "Training: 3 lives.\nResults aren't recorded in the Hall of Fame.\nDifficulty suitable for beginners.",
    hardcoreTooltip: "Hardcore: 1 life.\nOnly legends make the Hall of Fame!",
    hardcoreLoginPromptText: "Hardcore mode is recorded in the Hall of Fame, so it requires logging in with Discord.",
    hardcoreProfileUnavailableText:
      "Hardcore requires a server connection (bulbs are saved online). Try again in a moment.",
    normalLockedTooltip: "Not for you — you've already chosen the hard way.",
  },
  auth: {
    discordLoginLabel: "Log in with Discord",
    verifiedLabel: "Watchman identity verified: {name}",
    logoutLabel: "Log out",
  },
  game: {
    doorClosedLabel: "Door: CLOSED",
    doorOpenLabel: "Door: OPEN",
    lightOnLabel: "UV lights outside the door: on",
    lightOffLabel: "UV lights outside the door: off",
    lightBrokenLabel: "UV lights outside the door: bulb broken",
    lightControlTooltip:
      "There's probably the biggest bulb you've ever seen outside that door. The monster's roar tells you it's not just UV light.",
    lightBlockedByOpenDoorMessage: "Close the door first, or it'll fry you!",
    powerLabel: "Power",
    stressLabel: "Stress",
    bulbsLabel: "Bulbs",
    nearRoomBulbLabel: "Door bulb",
    bulbBrokenLabel: "broken",
    timeLabel: "Time until dawn",
    nightLabel: "Night {n}",
    camerasLabel: "Cameras",
    cameraOverviewHint: "Click a monitor for detail.",
    backToOverviewLabel: "Back to overview",
    cameraFocusingLabel: "TUNING SIGNAL...",
    sonicCannonOffLabel: "TURN ON SONIC CANNON",
    sonicCannonOnLabel: "SONIC CANNON: ACTIVE",
    cameraOfflineSignalLostLabel: "SIGNAL LOST",
    cameraOfflineOutOfServiceLabel: "CAMERA OUT OF SERVICE",
    cameraOfflineServiceAtLabel: "SERVICE AT 06:00",
    cameraOfflineMicActiveLabel: "MIC: ACTIVE",
    audioOnLabel: "Sound: on",
    audioOffLabel: "Sound: off",
    lookAtDoorLabel: "Turn to the door",
    lookAtDeskLabel: "Back to the desk",
    doorViewHintOpen: "Open the door",
    doorViewHintClose: "Close the door",
    doorViewHintCloseUrgent: "SLAM THE DOOR SHUT!",
    doorViewHintGeneratorOverload: "The lock isn't responding...",
    doorViewHintDestroyed: "The mechanism is destroyed.",
    bulbReplaceLabel: "Replace the bulb",
    bulbReplaceInProgressLabel: "Replacing bulb… {seconds}s",
    bulbReplaceProgressShortLabel: "{seconds}s",
    bulbReplaceSuccessLabel: "Bulb replaced.",
    lookAtGeneratorLabel: "Check the generator",
    lookAtLeftWallLabel: "Look at the wall to the left",
    leftWallBackLabel: "Back to the desk",
    startEmergencyRunLabel: "EMERGENCY EXPEDITION\nTO THE STORAGE WING",
    startEmergencyRunHuntingLabel: "Go hunting",
    emergencyRunDangerWarningLabel:
      "You want to leave the office you're supposed to protect? THAT'S A BAD IDEA. Don't do it unless you have absolutely no other choice.",
    emergencyRunHoldingLabel: "PREPARING EMERGENCY DEPARTURE… {seconds}s",
    emergencyRunEnergyRechargedLabel: "Battery brought back. Power +{amount}.",
    emergencyRunThreatFollowedLabel: "Looks like you didn't come back alone.\nClose the door!",
    emergencyRunMonsterReachedOfficeLabel: "The monster reached the office.\nCLOSE THE DOOR, FAST!",
    officeBreachCloseDoorLabel: "CLOSE THE DOOR, FAST!",
    officeBreachCloseDoorHintLabel: "Something's right behind the door.",
    officeBreachRestartGeneratorLabel: "RESTART THE GENERATOR.",
    officeBreachRestartGeneratorHintLabel: "The door's holding. Now the generator.",
    officeBreachReplaceBulbLabel: "Replace the bulb once the hallway is clear.",
    officeBreachReplaceBulbHintLabel: "Generator's running. Just the bulb left to replace.",
    turnToDoorLabel: "Turn to the door",
    turnToDoorUrgentLabel: "GET TO THE DOOR, FAST!",
    shotgunAcquiredLabel: "Shotgun found. Now you've at least got a chance to fight back.",
    shotgunAmmoReadyLabel: "Shotgun: {ammo}/{max}",
    shotgunAmmoEmptyLabel: "Shotgun: empty",
    doubleBarrelAmmoReadyLabel: "Double-barrel: {ammo}/{max}",
    doubleBarrelAmmoEmptyLabel: "Double-barrel: empty",
    requestAmmoLabel: "REQUEST AMMO ({ammo}/{max})",
    requestAmmoNoWeaponLabel: "You don't have a weapon. And you've thoroughly searched the whole office. You won't find one here.",
    startThinkItOverLabel: "Think it over",
    thinkItOverHoldingLabel: "Thinking… {seconds}s",
    officeDoorLockSliderLabel: "Office door lock: {seconds}s",
    officeDoorLockSliderHint: "How long the office door stays locked during an expedition before it opens on its own.",
    monsterHitConfirmedLabel: "Hit confirmed. The beast retreated into the dark.",
    monsterDefeatedRepeatLabel: "The beast is dead. But it wasn't the last one.",
    finalMonsterHitLabel: "The beast has fallen.",
    itemCollectedLabel: "{item} collected.",
    bulbAcquiredLabel: "Spare bulb stored in the supply room.",
    emergencyRunNeedsOpenDoorLabel: "You need to open the door first.",
    lookAtMapLabel: "Look at the map",
    mapBackLabel: "Back to the desk",
    generatorViewHint: "Click to restart.",
    generatorStateLabels: {
      normal: "Generator running.",
      silentFault: "The generator went quiet.",
      criticalBeeping: "FAULT! Restart the generator!",
      restarting: "Restarting...",
    },
    generatorAccidentalRestartMessage: "That was pretty dumb, what you just did...",
    generatorOverloadLabel: "OVERLOAD GENERATOR",
    generatorOverloadDangerLabel: "DANGER — IRREVERSIBLE DAMAGE",
    generatorOverloadHoldingLabel: "OVERLOAD IN {seconds}s",
    generatorOverloadWarningLabel: "WARNING: GENERATOR OVERLOAD\nReleasing the button cancels the action.",
    doorGeneratorOverloadCountdownLabel: "OVERLOAD: {seconds}s",
    titanOverloadDeathTitleLabel: "OVERLOAD COMPLETE",
    titanOverloadDeathBodyLabel: "Contact eliminated.\nThe security door was destroyed.",
    monsterReturnedUnverifiedHint: "You didn't know where it went. By the time you opened the door, it was already back.",
  },
  death: {
    gameOverLabel: "GAME OVER",
    title: "Shift ended early.",
    reasons: {
      door_open_at_attack: "Your last mistake was an open door.",
      blackout_timeout: "Power ran out. With no electricity, every security system stopped working.",
      bulb_replacement_attack: "Going to replace that bulb wasn't heroic — it was the last mistake of your life.",
      emergency_run: "The emergency expedition outside the office was the last one you ever took.",
      titan_ambush_emergency_run: "While trying to escape, the door jammed and the Titan killed you.",
      titan_door_breach: "The Titan broke through the security door. Nothing stopped it.",
    },
    corporateMessages: [
      "The position will be filled by another watchman.",
      "An employee's disappearance is no reason to interrupt operations.",
      "Object 13 continues normal operation.",
      "Operations were not disrupted by any incident.",
      "The post is ready for the next candidate.",
      "Recruitment for the vacant position continues.",
      "The facility has no record of any extraordinary event.",
      "The next watchman will be briefed on the same terms.",
    ],
    previousGuardsLabel: "Previous watchmen: {count}",
    normalContinueLivesLabel: "Lives remaining: {lives}",
    normalContinueNightLabel: "Retry night {night}.",
    normalContinueButton: "CONTINUE",
    normalGameOverLabel: "Out of lives. Shift over.",
    normalGameOverButton: "NEW GAME",
    normalLeaderboardNote: "Training isn't recorded in the Hall of Fame.",
    hardcoreGameOverLabel: "Hardcore run over. Death sends you back to night 1.",
    hardcoreGameOverButton: "NEW GAME",
  },
  blackout: {
    phaseTexts: [
      "The emergency battery took over power.",
      "The lock is weakening. Distant footsteps somewhere.",
      "The hallway went quiet. The footsteps are getting faster.",
      "Something's behind the door.",
    ] as const,
    subtitle: "The emergency battery is at zero.",
  },
  win: {
    title: "You survived the shift.",
    subtitle: "The sun is rising. Object 13 is quiet, for now.",
    retryButton: "Continue to the next night",
    backToMenuLabel: "Return to menu",
    survivedNightsLabel: {
      one: "Current watchman lasted: {count} night",
      few: "Current watchman lasted: {count} nights",
      many: "Current watchman lasted: {count} nights",
    },
  },
  night30Ending: {
    noKill: {
      epilogueText: null as string | null,
      recordNoteValue: "He still kept the first paycheck envelope on his desk. He never threw it away.",
    },
    warrior: {
      epilogueText:
        "A few days later\n\nAt home, you opened the briefcase again.\n\nThere was more money inside than you'd ever seen in one place.\n\nFor a moment you thought you'd never have to work again.\nMaybe ten years.\nMaybe more.\n\nThe first months were quiet.\nNo cameras.\nNo door.\nNo UV lights.\nNo generator.\n\nThen came the boredom.\n\nAnd then, an ordinary job." as string | null,
      recordNoteValue: "In the official records, Object 13 never existed.\nNeither did your part in it.",
    },
    continueLabel: "Continue",
    recordHeading: "15 years later",
    recordTitle: "DEATH RECORD",
    recordCauseLabel: "Cause of death:",
    recordCauseValue: "heart failure",
    recordFactorsLabel: "Contributing factors:",
    recordFactors: ["obesity", "sedentary occupation", "long-term lack of exercise"] as const,
    recordWeightLabel: "Weight at death:",
    recordWeightValue: "178 kg",
    recordTimeLabel: "Time of death:",
    recordTimeValue: "14:07",
    recordDescendantsLabel: "Descendants:",
    recordDescendantsValue: "none",
    recordNoteLabel: "Note:",
    backToMenuLabel: "Back to menu",
  },
  monsterDefeated: {
    title: "GAME OVER",
    subtitle: "...for the monster",
    body: "Congratulations.\nThis time, for real.\n\nYou earned your paycheck :-D",
    backToMenuButton: "BACK TO MENU",
    skipCinematicLabel: "Skip",
  },
  loading: {
    title: "OBJECT 13 — SERVICE TERMINAL",
    subtitle: "Starting shift systems...",
    difficultyNormalLabel: "Difficulty TRAINING",
  },
  footer: {
    projectName: "Night Watchman",
    aboutLinkLabel: "About",
    comingSoonLabel: "Coming soon: night-shift job listings",
    tagline: "A horror game and tribute to night shift workers.",
  },
  about: {
    seoTitle: "About | Night Watchman",
    seoDescription:
      "Night Watchman is a small browser horror game about a night shift, and a tribute to the people who really work at night.",
    heading: "About Night Watchman",
    paragraphs: [
      "Night Watchman is a small browser horror game about a night shift in a decaying facility. " +
        "The player watches cameras, manages power, checks the door, and tries to survive until morning.",
      "The project is also a tribute to the people who really work at night — watchmen, security guards, " +
        "doorkeepers, receptionists, warehouse workers, technicians, and others.",
      "The horror in the game is fiction. Real night work is often quiet, unnoticed, and undervalued.",
      "In the future I'd like to connect the site to useful offers for night-shift workers: jobs, " +
        "services, partnerships, or sponsorship.",
    ],
    ctaHeading: "Got a job offer, a collaboration idea, or interest in sponsorship?",
    ctaAction: "Get in touch:",
    backToGameLabel: "← Back to the game",
  },
  terms: {
    seoTitle: "Terms of Night Duty | Night Watchman",
    seoDescription: "Terms of night duty at Object 13 — half game lore, half disclaimer for the horror game Night Watchman.",
    heading: "Terms of Night Duty",
    paragraphs: [
      "By starting a shift at Object 13, you confirm that you are entering duty voluntarily, " +
        "of sound mind, and at your own responsibility.",
      "You acknowledge that during the shift, power outages, disorientation, unknown figures " +
        "on the camera system, sounds behind the door, and other phenomena may occur that the " +
        "operator may not be able to satisfactorily explain.",
      "You further acknowledge that Night Watchman is a horror game. It contains tension, " +
        "darkness, sudden noises, jump scares, disturbing imagery, and other elements that " +
        "may be unsuitable for sensitive individuals, people with heart conditions, epilepsy, " +
        "anxiety, or other health concerns.",
      "If you suffer from a medical condition, are playing while tired, stressed, alone in a " +
        "dark room, or with headphones set too loud, you do so at your own risk.",
      "Neither the game's operator nor the company responsible for running Object 13 accepts " +
        "liability for consequences arising from voluntarily starting a shift, including fright, " +
        "lost sleep, a suspicious glance down the hallway, a sudden urge to turn on the lights, " +
        "or a decision not to close the door in time.",
      "The night watchman is required to monitor the camera system, conserve power, check the " +
        "door, and avoid jumping to conclusions when something moved somewhere the records say " +
        "nothing should be.",
      "Leaving your post during a shift is not recommended. Leaving your post without a body is " +
        "not recorded as a workplace injury.",
      "In the event of disappearance, early termination of shift, or other operational " +
        "complication, the position may be filled by another watchman without undue delay.",
      "The \"Accept new watchman\" button does not mean the original employee is returning to " +
        "duty. It only means operations continue.",
      "All events at Object 13 are fictional. The game does not serve as an actual employment " +
        "document, medical advice, or safety training.",
      "The game is fiction. Night work is real. Real people working at night deserve respect, " +
        "light, peace, and a fair wage.",
    ],
    backLabel: "← Back to start",
  },
  leaderboard: {
    seoTitle: "Hall of Fame | Night Watchman",
    seoDescription: "Object 13 watchmen's Hall of Fame — who holds the record, and who's on duty right now.",
    heading: "Hall of Fame",
    subheading: "The position has been filled again and again. Some lasted longer than others.",
    explanation:
      "The record shows a player's best-ever shift. The current run shows a watchman who hasn't " +
      "come back yet — and hasn't disappeared either.",
    columnRank: "Rank",
    columnGuard: "Watchman",
    columnBestRun: "Record",
    columnCurrentRun: "Current run",
    noActiveRunLabel: "no active run",
    backToGameLabel: "← Back to the game",
  },
  achievements: {
    unlockedLabel: "Achievement unlocked",
    newResultsHeading: "NEW ACHIEVEMENT",
  },
  database: {
    seoTitle: "Object 13 Database",
    seoDescription: "Internal database of subjects, equipment, incidents, and operating manuals for Object 13.",
    facilityLabel: "OBJECT 13",
    databaseLabel: "INTERNAL DATABASE",
    accessLevelLabel: "Access level",
    accessLevelPublic: "PUBLIC PREVIEW",
    accessLevelStaff: "SECURITY STAFF",
    connectionStatusLabel: "Connection status",
    connectionStatusOnline: "ONLINE",
    introText:
      "This database contains records of test subjects, defensive equipment, night incidents, and operating procedures for Object 13.",
    introTextAuth: "Some information is available publicly. Personal records and player progress are shown only after logging in.",
    staffLabel: "Logged-in staff:",
    staffFallback: "AUTHORIZED USER",

    publicAccessHeading: "PUBLIC ACCESS",
    publicAccessIntro: "You are viewing the public section of the Object 13 database.",
    publicAccessFutureIntro: "After logging in, the following will become available here in the future:",
    publicAccessFutureItems: [
      "discovered subject types",
      "personal encounter statistics",
      "confirmed weaknesses",
      "your own night-shift reports",
      "incident history",
      "unlocked manuals",
      "equipment statistics",
      "research progress",
    ],
    loginButtonLabel: "LOG IN",

    personalRecordsHeading: "PERSONAL RECORDS",
    personalRecordsGuestText: "Log in to view your own progress, reports, and discovered findings.",
    personalRecordHeading: "PERSONAL RECORD",
    highestNightLabel: "Highest night reached:",
    discoveredSubjectsLabel: "Discovered subjects:",
    completedReportsLabel: "Completed reports:",
    confirmedKillsLabel: "Confirmed kills:",
    disabledCamerasLabel: "Disabled cameras:",
    notConnectedValue: "NOT CONNECTED YET",
    notTrackedValue: "NOT TRACKED",
    personalRecordTodo:
      "The logged-in player's actual data will be shown here later. Data will come from central game progress, not this page's local state.",

    tabSubjectsLabel: "Subjects",
    tabEquipmentLabel: "Equipment",
    tabReportsLabel: "Reports",
    tabManualsLabel: "Manuals",

    todoBadgeTodo: "TODO",
    todoBadgePlanned: "PLANNED FEATURE",
    todoDefaultDescription: "This section is a draft of a future feature. It isn't connected to game state or the player database yet.",

    backToGameLabel: "← Back to the game",
  },
  cinematics: {
    intro: {
      title: "JOB INTERVIEW",
      segments: {
        greeting: { text: "Good day. Thank you for coming.", responseLabel: "Continue." },
        profile_match: {
          text: "Your profile matches what we're looking for. For the last twenty years you worked as a night watchman at the local chemical plant, until it shut down.",
          responseLabel: "Continue.",
        },
        no_complaints: {
          text: "In all that time, not a single serious complaint. You're reliable, punctual, and used to working nights.",
          responseLabel: "Continue.",
        },
        no_dependents: {
          text: "I also see you have no children or close relatives depending on you. For this position, that's an advantage.",
          responseLabel: "Continue.",
        },
        hired: { text: "I'm pleased to tell you that you're hired.", responseLabel: "Continue." },
        special_place: {
          text: "This will be watching over a very special place. And a special place, of course, means special rewards too.",
          responseLabel: "Continue.",
        },
        risk_and_pay: {
          text: "The job pays above standard rates, and with good results you can earn extraordinary bonuses. At the same time, I must warn you that the position carries a certain risk.",
          responseLabel: "Continue.",
        },
        duties: {
          text: "Your job will be to monitor the cameras, check the equipment, and follow standard operating procedures.",
          responseLabel: "Continue.",
        },
        welcome: {
          text: "As long as you follow instructions, there shouldn't be any problem. Welcome to Object 13.",
          responseLabel: "Understood.",
        },
        payday_note: { text: "P.S.: Payday is every 30 days, standard.", responseLabel: "Understood." },
      },
    },
    old_guard_first_death_warning: {
      title: null as string | null,
      segments: {
        baf: { text: "Boo.", responseLabel: "..." },
        another_one: {
          text: "Oh, great. Another one staring at the monitors, not watching his own back.",
          responseLabel: "I gulp.",
        },
        im_the_tech: { text: "I'm the local technician. Lucky for you it's me.", responseLabel: "I stay quiet." },
        last_day: { text: "This is my last day here. I'm moving out of town.", responseLabel: "I listen." },
        advice_intro: { text: "So let me give you a few pointers as a farewell gift, new ear.", responseLabel: "..." },
        creatures: { text: "There are some strange creatures wandering around here. Real strange.", responseLabel: "I gulp." },
        cameras: { text: "What do you think those cameras are for, idiot?", responseLabel: "I stay quiet." },
        door_power: {
          text: "That door's electrified. Electricity eats power. You get that much, right?",
          responseLabel: "Got it.",
        },
        dont_panic_close: {
          text: "Don't see any danger on the cameras? Then don't close the door like some scared rabbit.",
          responseLabel: "Now I get it.",
        },
        watch_hallway: { text: "See something in the hallway? Watch where it goes.", responseLabel: "Okay." },
        close_the_door: {
          text: "Is it by the door? Then close it. Even a little kid would get that.",
          responseLabel: "Understood.",
        },
        light_tip: {
          text: "And sometimes it helps to turn the light on outside the door. Kids are scared of the dark too... hahaha.",
          responseLabel: "I gulp.",
        },
        farewell: { text: "Well, have a nice night.", responseLabel: "Back to the desk." },
      },
    },
    think_it_over_warning: {
      title: null as string | null,
      segments: {
        dont: { text: "Don't do it!", responseLabel: "..." },
        not_a_coward: { text: "I thought you weren't a coward who gives up that easily.", responseLabel: "I'm not." },
        find_warrior: { text: "Find the warrior in you.", responseLabel: "I'll try." },
        not_invincible: {
          text: "The monster isn't invincible — it's just tougher than it looks.",
          responseLabel: "I'm listening.",
        },
        heals: { text: "But remember: it heals again by morning.", responseLabel: "Got it." },
        one_night: {
          text: "If you want to put it down, you have to do it within a single night.",
          responseLabel: "Alright.",
        },
        one_two_hits: { text: "One shot just enrages it, two might rattle it…", responseLabel: "And then?" },
        ten_hits: {
          text: "…but facing your fear and pulling the trigger TEN times? That might just be enough to bring this beast down.",
          responseLabel: "Back to the desk, and into the fight.",
        },
      },
    },
    valhala_ending: {
      title: "VALHALLA",
      segments: {
        silence: { text: "Silence.", responseLabel: "..." },
        wood_creaked: {
          text: "Then wood creaked under your hands. You were sitting at a long table.",
          responseLabel: "I look around.",
        },
        hynek_raises_mug: { text: "Across from you, Hynek raised a mug of beer.", responseLabel: "..." },
        close_call: { text: "\"You were close.\"", responseLabel: "I stay quiet." },
        smiled: { text: "He smiled for a moment.", responseLabel: "..." },
        thirty_or_valhalla: {
          text: "\"In the end, I was right. Either we meet on the thirtieth night… or in Valhalla.\"",
          responseLabel: "I'm listening.",
        },
        pushed_beer: { text: "He slid a beer over to you.", responseLabel: "..." },
        not_bad_guard: {
          text: "\"And you know what? You didn't do badly as a watchman.\"",
          responseLabel: "I take a drink.",
        },
      },
    },
    warrior_ending: {
      title: "THE LAST SHIFT",
      segments: {
        thirtieth_day: { text: "The thirtieth day.", responseLabel: "..." },
        hynek_smiling: {
          text: "Hynek stood in the middle of the room, smiling more than usual.",
          responseLabel: "I watch him.",
        },
        not_just_good_watch: { text: "\"Alright. This wasn't just a good watch anymore.\"", responseLabel: "..." },
        nodded: { text: "He looked at you and nodded.", responseLabel: "..." },
        you_became_warrior: { text: "\"You became a warrior.\"", responseLabel: "I stay quiet." },
        men_in_suits: {
          text: "Behind him came the sound of metal, footsteps, and the muffled voices of men in protective suits.",
          responseLabel: "I'm listening.",
        },
        thank_you_bait: {
          text: "\"And most of all — thank you. You helped me test the monster bait.\"",
          responseLabel: "What?",
        },
        points_at_generator: { text: "He pointed at the generator.", responseLabel: "..." },
        your_generator: { text: "\"Yeah. That one. Your generator.\"", responseLabel: "..." },
        let_it_sink_in: { text: "He let you sit with what he'd just said for a moment.", responseLabel: "..." },
        not_out_of_town: { text: "\"Honestly… I was never out of town.\"", responseLabel: "..." },
        you_bought_time: {
          text: "\"You just bought me time. Time to finish the preparations.\"",
          responseLabel: "Got it.",
        },
        lights_on: { text: "Lights switched on behind Hynek.", responseLabel: "..." },
        maximum_fireworks: {
          text: "\"In a moment we'll turn it up to maximum. And prepare a truly big fireworks show.\"",
          responseLabel: "...",
        },
        opened_briefcase: { text: "He handed you an open briefcase full of money.", responseLabel: "..." },
        your_pay_plus_bonus: {
          text: "\"This is your pay. And a little extra for your silence.\"",
          responseLabel: "I take it.",
        },
        grew_serious: { text: "Then he turned serious.", responseLabel: "..." },
        thousand_monsters: {
          text: "\"We need to go. Once we start this up, it might draw a thousand monsters.\"",
          responseLabel: "I run.",
        },
        step_to_door: { text: "He stepped toward the door.", responseLabel: "..." },
        project_ends: { text: "\"The whole project ends with this. You did your job.\"", responseLabel: "..." },
        turned_back: { text: "He turned back once more.", responseLabel: "..." },
        good_luck_warrior: {
          text: "\"Good luck in your new job. And thanks, warrior.\"",
          responseLabel: "Farewell.",
        },
      },
    },
    no_kill_ending: {
      title: "FIRST PAYCHECK",
      segments: {
        thirtieth_day: { text: "The thirtieth day.", responseLabel: "..." },
        hynek_before_dawn: {
          text: "Hynek appeared in the doorway before dawn had even broken.",
          responseLabel: "...",
        },
        looked_you_over: { text: "He just looked you over for a moment.", responseLabel: "I wait." },
        thirty_nights: {
          text: "\"Thirty nights. No escape. No heroics. No unnecessary questions.\"",
          responseLabel: "...",
        },
        handed_envelope: { text: "He handed you an envelope.", responseLabel: "..." },
        good_guard: { text: "\"You were a good watchman.\"", responseLabel: "Thanks." },
        waited_for_truth: {
          text: "You waited for an explanation. You waited for the truth. You waited for something to end after thirty nights.",
          responseLabel: "...",
        },
        lit_cigarette: { text: "Hynek just lit a cigarette.", responseLabel: "..." },
        see_you_in_a_month: { text: "\"Well, see you again in a month.\"", responseLabel: "Back to the desk." },
      },
    },
  },
  achievementDefinitions: {
    meet_hynek: {
      title: "Meeting Hynek",
      description: "Died on the very first day.",
    },
  },
  playerAchievements: {
    first_shift: { title: "First shift", description: "You started your first night shift." },
    first_death: { title: "First end of duty", description: "Object 13 showed you this wouldn't be an ordinary job." },
    hynek_encounter: { title: "Meeting Hynek", description: "You died on the very first night." },
    first_expedition: { title: "Out of the office", description: "You left the safety of the office for the first time." },
    first_bulb_replaced: { title: "Spare bulb", description: "You replaced a broken bulb for the first time." },
    first_generator_restart: { title: "Restart and pray", description: "You restarted the generator for the first time." },
    first_monster_hit: { title: "First blood", description: "You confirmed a hit on the beast for the first time." },
    not_a_rookie_anymore: { title: "Not a rookie anymore", description: "You defeated the beast for the first time." },
    golden_guard: { title: "Double-barrel watchman", description: "You unlocked the double-barrel shotgun." },
    hardcore_night_5: { title: "Hard duty", description: "You reached at least night 5 in Hardcore mode." },
    hardcore_night_10: { title: "Start getting used to it", description: "You reached at least night 10 in Hardcore mode." },
    hardcore_night_20: { title: "Just routine now", description: "You reached at least night 20 in Hardcore mode." },
    hardcore_night_30: { title: "Your first paycheck", description: "You reached at least night 30 in Hardcore mode." },
    monster_slayer: { title: "Beast slayer", description: "You killed the beast a second time." },
  },
  monsterDefeatedCinematicCaptions: {
    congrats_not_a_rookie: "Congratulations — I'll admit you're not a rookie anymore!",
    warrior_spirit: "You've got the spirit of a fighter in you.",
    not_first_not_last: "But trust me, that beast wasn't the first, and it won't be the last.",
    more_will_come: "More will come.",
    reward_for_you: "I've got something for you as a reward.",
    left_on_office_wall: "I left it for you on the office wall.",
    want_to_know_truth: "Want to know what this is really about?",
    meet_on_day_30: "We'll meet again on day 30...",
    or_in_valhalla: "...or in Valhalla.",
  },
  radio: {
    interceptedTransmissionLabel: "INTERCEPTED TRANSMISSION",
    transmissionStatusLabel: "Transmission in progress…",
    ghoulCameraAttackWarningText: "Oh no! The sonic cannon attracted a ghoul!",
    cameraDisabledMessages: {
      radio_camera_destroyed_0: "Well, looks like we're in the dark till morning.",
      radio_camera_destroyed_1: "Camera destroyed!",
      radio_camera_destroyed_2: "Only the microphone's left now.",
    },
    titanEscapeMessages: {
      titan_escape_01: "Damn it, the Titan got loose! Doors and lights won't stop it. Think of something stronger!",
      titan_escape_02: "The Titan's outside! Standard defenses aren't working. Use everything you've got!",
      titan_escape_03: "You won't shoot it down or hold it behind the door. Think of something, fast!",
      titan_escape_04: "The Titan's heading your way! Weapons are useless. You need something bigger!",
      titan_escape_05: "God… the Titan got out. Use something that can take down the whole system!",
    },
  },
  ui: {
    mobileLandscapeHint: "For a better experience, turn your phone sideways.",
    adminBadgeLabel: "You're an ADMIN!",
  },
  loadingHints: {
    energy_generator_battery: "The old generator barely keeps the facility alive — at night you're running on battery reserve.",
    doors_magnetic_lock: "The magnetic lock only holds the door shut while powered. Don't leave it closed longer than you need to.",
    cameras_power_drain: "Cameras drain power. Turn them off and the battery slowly recharges.",
    generator_normal_beep: "The generator beeps every five seconds. If it goes quiet, something's wrong.",
    blackout_lock_release: "During a blackout the lock releases. The door is no longer your safety net.",
    controls_look_at_door: "You have to turn to the door first. Only then can you close it.",
    enemy_route_variance: "Whatever's on camera doesn't always take the same route.",
    lore_day_only_design: "Object 13 was designed for daytime operation. Nobody ever properly tested the night shift mode.",
  },
};
